# Generated by Django 4.2 on 2024-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
