# Generated by Django 4.2 on 2024-09-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_likes_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="likes_count",
        ),
    ]
