# Generated by Django 4.2 on 2024-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_remove_article_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
