# Generated by Django 4.2 on 2024-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_likes_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="likes_count",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
