# Generated by Django 4.2 on 2024-09-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
