# Generated by Django 4.2 on 2024-09-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_image_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image_field",
            new_name="image",
        ),
    ]
