# Generated by Django 4.2 on 2024-09-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_image_field_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.AddField(
            model_name="user",
            name="image_field",
            field=models.ImageField(default="static/default/", upload_to=""),
        ),
    ]
