# Generated by Django 4.2 on 2024-09-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_article_alter_user_email"),
        ("accounts", "0007_remove_user_image_user_image_field"),
    ]

    operations = []
