# Generated by Django 4.2 on 2024-09-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20240912_0637"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
